<?php
/**
 * CompteApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * CompteApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CompteApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteCompteItem
     *
     * Removes the Compte resource..
     *
     */
    public function testDeleteCompteItem()
    {
    }

    /**
     * Test case for getCompteCollection
     *
     * Retrieves the collection of Compte resources..
     *
     */
    public function testGetCompteCollection()
    {
    }

    /**
     * Test case for getCompteItem
     *
     * Retrieves a Compte resource..
     *
     */
    public function testGetCompteItem()
    {
    }

    /**
     * Test case for patchCompteItem
     *
     * Updates the Compte resource..
     *
     */
    public function testPatchCompteItem()
    {
    }

    /**
     * Test case for postCompteCollection
     *
     * Creates a Compte resource..
     *
     */
    public function testPostCompteCollection()
    {
    }

    /**
     * Test case for putCompteItem
     *
     * Replaces the Compte resource..
     *
     */
    public function testPutCompteItem()
    {
    }
}
