<?php
/**
 * EvenementsAttenteApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * EvenementsAttenteApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EvenementsAttenteApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteEvenementsAttenteItem
     *
     * Removes the EvenementsAttente resource..
     *
     */
    public function testDeleteEvenementsAttenteItem()
    {
    }

    /**
     * Test case for getEvenementsAttenteCollection
     *
     * Retrieves the collection of EvenementsAttente resources..
     *
     */
    public function testGetEvenementsAttenteCollection()
    {
    }

    /**
     * Test case for getEvenementsAttenteItem
     *
     * Retrieves a EvenementsAttente resource..
     *
     */
    public function testGetEvenementsAttenteItem()
    {
    }

    /**
     * Test case for patchEvenementsAttenteItem
     *
     * Updates the EvenementsAttente resource..
     *
     */
    public function testPatchEvenementsAttenteItem()
    {
    }

    /**
     * Test case for postEvenementsAttenteCollection
     *
     * Creates a EvenementsAttente resource..
     *
     */
    public function testPostEvenementsAttenteCollection()
    {
    }

    /**
     * Test case for putEvenementsAttenteItem
     *
     * Replaces the EvenementsAttente resource..
     *
     */
    public function testPutEvenementsAttenteItem()
    {
    }
}
