<?php
/**
 * PhotoApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * PhotoApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PhotoApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deletePhotoItem
     *
     * Removes the Photo resource..
     *
     */
    public function testDeletePhotoItem()
    {
    }

    /**
     * Test case for getPhotoCollection
     *
     * Retrieves the collection of Photo resources..
     *
     */
    public function testGetPhotoCollection()
    {
    }

    /**
     * Test case for getPhotoItem
     *
     * Retrieves a Photo resource..
     *
     */
    public function testGetPhotoItem()
    {
    }

    /**
     * Test case for patchPhotoItem
     *
     * Updates the Photo resource..
     *
     */
    public function testPatchPhotoItem()
    {
    }

    /**
     * Test case for postPhotoCollection
     *
     * Creates a Photo resource..
     *
     */
    public function testPostPhotoCollection()
    {
    }

    /**
     * Test case for putPhotoItem
     *
     * Replaces the Photo resource..
     *
     */
    public function testPutPhotoItem()
    {
    }
}
