//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photobooth
{
    using System;
    using System.Collections.Generic;
    
    public partial class compte_has_photo
    {
        public int Photo_idPhoto { get; set; }
        public int Evenements_idEvenements { get; set; }
        public Nullable<int> Compte_idCompte { get; set; }
    
        public virtual compte compte { get; set; }
        public virtual evenements evenements { get; set; }
        public virtual photo photo { get; set; }
    }
}
