//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photobooth
{
    using System;
    using System.Collections.Generic;
    
    public partial class evenements_attente
    {
        public int idEvenements_Attente { get; set; }
        public string Nom { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateDeFin { get; set; }
        public string MotDePasseEvent { get; set; }
        public int IdCompte { get; set; }
    }
}
