//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photobooth
{
    using System;
    using System.Collections.Generic;
    
    public partial class evenements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evenements()
        {
            this.compte_has_photo = new HashSet<compte_has_photo>();
        }
    
        public int idEvenements { get; set; }
        public string Nom { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateDeFin { get; set; }
        public string MotDePasseEvent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compte_has_photo> compte_has_photo { get; set; }
    }
}
