//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photobooth
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class photoboothproject_2020Entities : DbContext
    {
        public photoboothproject_2020Entities()
            : base("name=photoboothproject_2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<compte> compte { get; set; }
        public virtual DbSet<evenements> evenements { get; set; }
        public virtual DbSet<evenements_attente> evenements_attente { get; set; }
        public virtual DbSet<photo> photo { get; set; }
    }
}
