/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IEvenementsAttenteApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Removes the EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns></returns>
        void DeleteEvenementsAttenteItem (string id);

        /// <summary>
        /// Removes the EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteEvenementsAttenteItemWithHttpInfo (string id);
        /// <summary>
        /// Retrieves the collection of EvenementsAttente resources.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>Object</returns>
        Object GetEvenementsAttenteCollection (int? page = null);

        /// <summary>
        /// Retrieves the collection of EvenementsAttente resources.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> GetEvenementsAttenteCollectionWithHttpInfo (int? page = null);
        /// <summary>
        /// Retrieves a EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ComponentsschemasEvenementsAttentejsonld</returns>
        ComponentsschemasEvenementsAttentejsonld GetEvenementsAttenteItem (string id);

        /// <summary>
        /// Retrieves a EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of ComponentsschemasEvenementsAttentejsonld</returns>
        ApiResponse<ComponentsschemasEvenementsAttentejsonld> GetEvenementsAttenteItemWithHttpInfo (string id);
        /// <summary>
        /// Updates the EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>ComponentsschemasEvenementsAttentejsonld</returns>
        ComponentsschemasEvenementsAttentejsonld PatchEvenementsAttenteItem (string id, EvenementsAttente body = null);

        /// <summary>
        /// Updates the EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>ApiResponse of ComponentsschemasEvenementsAttentejsonld</returns>
        ApiResponse<ComponentsschemasEvenementsAttentejsonld> PatchEvenementsAttenteItemWithHttpInfo (string id, EvenementsAttente body = null);
        /// <summary>
        /// Creates a EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The new EvenementsAttente resource (optional)</param>
        /// <returns>ComponentsschemasEvenementsAttentejsonld</returns>
        ComponentsschemasEvenementsAttentejsonld PostEvenementsAttenteCollection (EvenementsAttente body = null);

        /// <summary>
        /// Creates a EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The new EvenementsAttente resource (optional)</param>
        /// <returns>ApiResponse of ComponentsschemasEvenementsAttentejsonld</returns>
        ApiResponse<ComponentsschemasEvenementsAttentejsonld> PostEvenementsAttenteCollectionWithHttpInfo (EvenementsAttente body = null);
        /// <summary>
        /// Replaces the EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>ComponentsschemasEvenementsAttentejsonld</returns>
        ComponentsschemasEvenementsAttentejsonld PutEvenementsAttenteItem (string id, EvenementsAttente body = null);

        /// <summary>
        /// Replaces the EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>ApiResponse of ComponentsschemasEvenementsAttentejsonld</returns>
        ApiResponse<ComponentsschemasEvenementsAttentejsonld> PutEvenementsAttenteItemWithHttpInfo (string id, EvenementsAttente body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Removes the EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteEvenementsAttenteItemAsync (string id);

        /// <summary>
        /// Removes the EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteEvenementsAttenteItemAsyncWithHttpInfo (string id);
        /// <summary>
        /// Retrieves the collection of EvenementsAttente resources.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> GetEvenementsAttenteCollectionAsync (int? page = null);

        /// <summary>
        /// Retrieves the collection of EvenementsAttente resources.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GetEvenementsAttenteCollectionAsyncWithHttpInfo (int? page = null);
        /// <summary>
        /// Retrieves a EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ComponentsschemasEvenementsAttentejsonld</returns>
        System.Threading.Tasks.Task<ComponentsschemasEvenementsAttentejsonld> GetEvenementsAttenteItemAsync (string id);

        /// <summary>
        /// Retrieves a EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse (ComponentsschemasEvenementsAttentejsonld)</returns>
        System.Threading.Tasks.Task<ApiResponse<ComponentsschemasEvenementsAttentejsonld>> GetEvenementsAttenteItemAsyncWithHttpInfo (string id);
        /// <summary>
        /// Updates the EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>Task of ComponentsschemasEvenementsAttentejsonld</returns>
        System.Threading.Tasks.Task<ComponentsschemasEvenementsAttentejsonld> PatchEvenementsAttenteItemAsync (string id, EvenementsAttente body = null);

        /// <summary>
        /// Updates the EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>Task of ApiResponse (ComponentsschemasEvenementsAttentejsonld)</returns>
        System.Threading.Tasks.Task<ApiResponse<ComponentsschemasEvenementsAttentejsonld>> PatchEvenementsAttenteItemAsyncWithHttpInfo (string id, EvenementsAttente body = null);
        /// <summary>
        /// Creates a EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The new EvenementsAttente resource (optional)</param>
        /// <returns>Task of ComponentsschemasEvenementsAttentejsonld</returns>
        System.Threading.Tasks.Task<ComponentsschemasEvenementsAttentejsonld> PostEvenementsAttenteCollectionAsync (EvenementsAttente body = null);

        /// <summary>
        /// Creates a EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The new EvenementsAttente resource (optional)</param>
        /// <returns>Task of ApiResponse (ComponentsschemasEvenementsAttentejsonld)</returns>
        System.Threading.Tasks.Task<ApiResponse<ComponentsschemasEvenementsAttentejsonld>> PostEvenementsAttenteCollectionAsyncWithHttpInfo (EvenementsAttente body = null);
        /// <summary>
        /// Replaces the EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>Task of ComponentsschemasEvenementsAttentejsonld</returns>
        System.Threading.Tasks.Task<ComponentsschemasEvenementsAttentejsonld> PutEvenementsAttenteItemAsync (string id, EvenementsAttente body = null);

        /// <summary>
        /// Replaces the EvenementsAttente resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>Task of ApiResponse (ComponentsschemasEvenementsAttentejsonld)</returns>
        System.Threading.Tasks.Task<ApiResponse<ComponentsschemasEvenementsAttentejsonld>> PutEvenementsAttenteItemAsyncWithHttpInfo (string id, EvenementsAttente body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class EvenementsAttenteApi : IEvenementsAttenteApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EvenementsAttenteApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EvenementsAttenteApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EvenementsAttenteApi"/> class
        /// </summary>
        /// <returns></returns>
        public EvenementsAttenteApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EvenementsAttenteApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EvenementsAttenteApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Removes the EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns></returns>
        public void DeleteEvenementsAttenteItem (string id)
        {
             DeleteEvenementsAttenteItemWithHttpInfo(id);
        }

        /// <summary>
        /// Removes the EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteEvenementsAttenteItemWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling EvenementsAttenteApi->DeleteEvenementsAttenteItem");

            var localVarPath = "/PhotoBoothProject/evenements_attentes/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteEvenementsAttenteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Removes the EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteEvenementsAttenteItemAsync (string id)
        {
             await DeleteEvenementsAttenteItemAsyncWithHttpInfo(id);

        }

        /// <summary>
        /// Removes the EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteEvenementsAttenteItemAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling EvenementsAttenteApi->DeleteEvenementsAttenteItem");

            var localVarPath = "/PhotoBoothProject/evenements_attentes/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteEvenementsAttenteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Retrieves the collection of EvenementsAttente resources. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>Object</returns>
        public Object GetEvenementsAttenteCollection (int? page = null)
        {
             ApiResponse<Object> localVarResponse = GetEvenementsAttenteCollectionWithHttpInfo(page);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves the collection of EvenementsAttente resources. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > GetEvenementsAttenteCollectionWithHttpInfo (int? page = null)
        {

            var localVarPath = "/PhotoBoothProject/evenements_attentes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/ld+json",
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEvenementsAttenteCollection", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Retrieves the collection of EvenementsAttente resources. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> GetEvenementsAttenteCollectionAsync (int? page = null)
        {
             ApiResponse<Object> localVarResponse = await GetEvenementsAttenteCollectionAsyncWithHttpInfo(page);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves the collection of EvenementsAttente resources. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> GetEvenementsAttenteCollectionAsyncWithHttpInfo (int? page = null)
        {

            var localVarPath = "/PhotoBoothProject/evenements_attentes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/ld+json",
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEvenementsAttenteCollection", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Retrieves a EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ComponentsschemasEvenementsAttentejsonld</returns>
        public ComponentsschemasEvenementsAttentejsonld GetEvenementsAttenteItem (string id)
        {
             ApiResponse<ComponentsschemasEvenementsAttentejsonld> localVarResponse = GetEvenementsAttenteItemWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of ComponentsschemasEvenementsAttentejsonld</returns>
        public ApiResponse< ComponentsschemasEvenementsAttentejsonld > GetEvenementsAttenteItemWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling EvenementsAttenteApi->GetEvenementsAttenteItem");

            var localVarPath = "/PhotoBoothProject/evenements_attentes/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/ld+json",
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEvenementsAttenteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentsschemasEvenementsAttentejsonld>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ComponentsschemasEvenementsAttentejsonld) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentsschemasEvenementsAttentejsonld)));
        }

        /// <summary>
        /// Retrieves a EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ComponentsschemasEvenementsAttentejsonld</returns>
        public async System.Threading.Tasks.Task<ComponentsschemasEvenementsAttentejsonld> GetEvenementsAttenteItemAsync (string id)
        {
             ApiResponse<ComponentsschemasEvenementsAttentejsonld> localVarResponse = await GetEvenementsAttenteItemAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves a EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse (ComponentsschemasEvenementsAttentejsonld)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ComponentsschemasEvenementsAttentejsonld>> GetEvenementsAttenteItemAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling EvenementsAttenteApi->GetEvenementsAttenteItem");

            var localVarPath = "/PhotoBoothProject/evenements_attentes/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/ld+json",
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEvenementsAttenteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentsschemasEvenementsAttentejsonld>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ComponentsschemasEvenementsAttentejsonld) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentsschemasEvenementsAttentejsonld)));
        }

        /// <summary>
        /// Updates the EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>ComponentsschemasEvenementsAttentejsonld</returns>
        public ComponentsschemasEvenementsAttentejsonld PatchEvenementsAttenteItem (string id, EvenementsAttente body = null)
        {
             ApiResponse<ComponentsschemasEvenementsAttentejsonld> localVarResponse = PatchEvenementsAttenteItemWithHttpInfo(id, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Updates the EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>ApiResponse of ComponentsschemasEvenementsAttentejsonld</returns>
        public ApiResponse< ComponentsschemasEvenementsAttentejsonld > PatchEvenementsAttenteItemWithHttpInfo (string id, EvenementsAttente body = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling EvenementsAttenteApi->PatchEvenementsAttenteItem");

            var localVarPath = "/PhotoBoothProject/evenements_attentes/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/merge-patch+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/ld+json",
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PatchEvenementsAttenteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentsschemasEvenementsAttentejsonld>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ComponentsschemasEvenementsAttentejsonld) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentsschemasEvenementsAttentejsonld)));
        }

        /// <summary>
        /// Updates the EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>Task of ComponentsschemasEvenementsAttentejsonld</returns>
        public async System.Threading.Tasks.Task<ComponentsschemasEvenementsAttentejsonld> PatchEvenementsAttenteItemAsync (string id, EvenementsAttente body = null)
        {
             ApiResponse<ComponentsschemasEvenementsAttentejsonld> localVarResponse = await PatchEvenementsAttenteItemAsyncWithHttpInfo(id, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Updates the EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>Task of ApiResponse (ComponentsschemasEvenementsAttentejsonld)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ComponentsschemasEvenementsAttentejsonld>> PatchEvenementsAttenteItemAsyncWithHttpInfo (string id, EvenementsAttente body = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling EvenementsAttenteApi->PatchEvenementsAttenteItem");

            var localVarPath = "/PhotoBoothProject/evenements_attentes/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/merge-patch+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/ld+json",
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PatchEvenementsAttenteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentsschemasEvenementsAttentejsonld>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ComponentsschemasEvenementsAttentejsonld) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentsschemasEvenementsAttentejsonld)));
        }

        /// <summary>
        /// Creates a EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The new EvenementsAttente resource (optional)</param>
        /// <returns>ComponentsschemasEvenementsAttentejsonld</returns>
        public ComponentsschemasEvenementsAttentejsonld PostEvenementsAttenteCollection (EvenementsAttente body = null)
        {
             ApiResponse<ComponentsschemasEvenementsAttentejsonld> localVarResponse = PostEvenementsAttenteCollectionWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The new EvenementsAttente resource (optional)</param>
        /// <returns>ApiResponse of ComponentsschemasEvenementsAttentejsonld</returns>
        public ApiResponse< ComponentsschemasEvenementsAttentejsonld > PostEvenementsAttenteCollectionWithHttpInfo (EvenementsAttente body = null)
        {

            var localVarPath = "/PhotoBoothProject/evenements_attentes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/ld+json", 
                "application/json", 
                "text/html"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/ld+json",
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostEvenementsAttenteCollection", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentsschemasEvenementsAttentejsonld>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ComponentsschemasEvenementsAttentejsonld) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentsschemasEvenementsAttentejsonld)));
        }

        /// <summary>
        /// Creates a EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The new EvenementsAttente resource (optional)</param>
        /// <returns>Task of ComponentsschemasEvenementsAttentejsonld</returns>
        public async System.Threading.Tasks.Task<ComponentsschemasEvenementsAttentejsonld> PostEvenementsAttenteCollectionAsync (EvenementsAttente body = null)
        {
             ApiResponse<ComponentsschemasEvenementsAttentejsonld> localVarResponse = await PostEvenementsAttenteCollectionAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creates a EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The new EvenementsAttente resource (optional)</param>
        /// <returns>Task of ApiResponse (ComponentsschemasEvenementsAttentejsonld)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ComponentsschemasEvenementsAttentejsonld>> PostEvenementsAttenteCollectionAsyncWithHttpInfo (EvenementsAttente body = null)
        {

            var localVarPath = "/PhotoBoothProject/evenements_attentes";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/ld+json", 
                "application/json", 
                "text/html"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/ld+json",
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostEvenementsAttenteCollection", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentsschemasEvenementsAttentejsonld>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ComponentsschemasEvenementsAttentejsonld) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentsschemasEvenementsAttentejsonld)));
        }

        /// <summary>
        /// Replaces the EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>ComponentsschemasEvenementsAttentejsonld</returns>
        public ComponentsschemasEvenementsAttentejsonld PutEvenementsAttenteItem (string id, EvenementsAttente body = null)
        {
             ApiResponse<ComponentsschemasEvenementsAttentejsonld> localVarResponse = PutEvenementsAttenteItemWithHttpInfo(id, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Replaces the EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>ApiResponse of ComponentsschemasEvenementsAttentejsonld</returns>
        public ApiResponse< ComponentsschemasEvenementsAttentejsonld > PutEvenementsAttenteItemWithHttpInfo (string id, EvenementsAttente body = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling EvenementsAttenteApi->PutEvenementsAttenteItem");

            var localVarPath = "/PhotoBoothProject/evenements_attentes/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/ld+json", 
                "application/json", 
                "text/html"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/ld+json",
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PutEvenementsAttenteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentsschemasEvenementsAttentejsonld>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ComponentsschemasEvenementsAttentejsonld) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentsschemasEvenementsAttentejsonld)));
        }

        /// <summary>
        /// Replaces the EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>Task of ComponentsschemasEvenementsAttentejsonld</returns>
        public async System.Threading.Tasks.Task<ComponentsschemasEvenementsAttentejsonld> PutEvenementsAttenteItemAsync (string id, EvenementsAttente body = null)
        {
             ApiResponse<ComponentsschemasEvenementsAttentejsonld> localVarResponse = await PutEvenementsAttenteItemAsyncWithHttpInfo(id, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Replaces the EvenementsAttente resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body">The updated EvenementsAttente resource (optional)</param>
        /// <returns>Task of ApiResponse (ComponentsschemasEvenementsAttentejsonld)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ComponentsschemasEvenementsAttentejsonld>> PutEvenementsAttenteItemAsyncWithHttpInfo (string id, EvenementsAttente body = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling EvenementsAttenteApi->PutEvenementsAttenteItem");

            var localVarPath = "/PhotoBoothProject/evenements_attentes/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/ld+json", 
                "application/json", 
                "text/html"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/ld+json",
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PutEvenementsAttenteItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ComponentsschemasEvenementsAttentejsonld>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ComponentsschemasEvenementsAttentejsonld) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ComponentsschemasEvenementsAttentejsonld)));
        }

    }
}
