<?php
/**
 * CompteHasPhoto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * CompteHasPhoto Class Doc Comment
 *
 * @category Class
 * @description CompteHasPhoto
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CompteHasPhoto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CompteHasPhoto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'compte_idcompte' => 'string',
'evenements_idevenements' => 'string',
'photo_idphoto' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'compte_idcompte' => 'iri-reference',
'evenements_idevenements' => 'iri-reference',
'photo_idphoto' => 'iri-reference'    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'compte_idcompte' => 'compteIdcompte',
'evenements_idevenements' => 'evenementsIdevenements',
'photo_idphoto' => 'photoIdphoto'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'compte_idcompte' => 'setCompteIdcompte',
'evenements_idevenements' => 'setEvenementsIdevenements',
'photo_idphoto' => 'setPhotoIdphoto'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'compte_idcompte' => 'getCompteIdcompte',
'evenements_idevenements' => 'getEvenementsIdevenements',
'photo_idphoto' => 'getPhotoIdphoto'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['compte_idcompte'] = isset($data['compte_idcompte']) ? $data['compte_idcompte'] : null;
        $this->container['evenements_idevenements'] = isset($data['evenements_idevenements']) ? $data['evenements_idevenements'] : null;
        $this->container['photo_idphoto'] = isset($data['photo_idphoto']) ? $data['photo_idphoto'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets compte_idcompte
     *
     * @return string
     */
    public function getCompteIdcompte()
    {
        return $this->container['compte_idcompte'];
    }

    /**
     * Sets compte_idcompte
     *
     * @param string $compte_idcompte compte_idcompte
     *
     * @return $this
     */
    public function setCompteIdcompte($compte_idcompte)
    {
        $this->container['compte_idcompte'] = $compte_idcompte;

        return $this;
    }

    /**
     * Gets evenements_idevenements
     *
     * @return string
     */
    public function getEvenementsIdevenements()
    {
        return $this->container['evenements_idevenements'];
    }

    /**
     * Sets evenements_idevenements
     *
     * @param string $evenements_idevenements evenements_idevenements
     *
     * @return $this
     */
    public function setEvenementsIdevenements($evenements_idevenements)
    {
        $this->container['evenements_idevenements'] = $evenements_idevenements;

        return $this;
    }

    /**
     * Gets photo_idphoto
     *
     * @return string
     */
    public function getPhotoIdphoto()
    {
        return $this->container['photo_idphoto'];
    }

    /**
     * Sets photo_idphoto
     *
     * @param string $photo_idphoto photo_idphoto
     *
     * @return $this
     */
    public function setPhotoIdphoto($photo_idphoto)
    {
        $this->container['photo_idphoto'] = $photo_idphoto;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
