api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    title: 'PhotoBoothProject'
    description: "Service Web"

    version: '1.0.0'
   #patch_formats:
        #json: ['application/merge-patch+json']
    swagger:
        versions: [3]
