/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Comptejsonld
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ComptejsonldTests
    {
        // TODO uncomment below to declare an instance variable for Comptejsonld
        //private Comptejsonld instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Comptejsonld
            //instance = new Comptejsonld();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Comptejsonld
        /// </summary>
        [Test]
        public void ComptejsonldInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Comptejsonld
            //Assert.IsInstanceOfType<Comptejsonld> (instance, "variable 'instance' is a Comptejsonld");
        }


        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Test]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Idcompte'
        /// </summary>
        [Test]
        public void IdcompteTest()
        {
            // TODO unit test for the property 'Idcompte'
        }
        /// <summary>
        /// Test the property 'Nom'
        /// </summary>
        [Test]
        public void NomTest()
        {
            // TODO unit test for the property 'Nom'
        }
        /// <summary>
        /// Test the property 'Prenom'
        /// </summary>
        [Test]
        public void PrenomTest()
        {
            // TODO unit test for the property 'Prenom'
        }
        /// <summary>
        /// Test the property 'Motdepasse'
        /// </summary>
        [Test]
        public void MotdepasseTest()
        {
            // TODO unit test for the property 'Motdepasse'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
