/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CompteHasPhotojsonld
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CompteHasPhotojsonldTests
    {
        // TODO uncomment below to declare an instance variable for CompteHasPhotojsonld
        //private CompteHasPhotojsonld instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CompteHasPhotojsonld
            //instance = new CompteHasPhotojsonld();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompteHasPhotojsonld
        /// </summary>
        [Test]
        public void CompteHasPhotojsonldInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CompteHasPhotojsonld
            //Assert.IsInstanceOfType<CompteHasPhotojsonld> (instance, "variable 'instance' is a CompteHasPhotojsonld");
        }


        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Test]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'CompteIdcompte'
        /// </summary>
        [Test]
        public void CompteIdcompteTest()
        {
            // TODO unit test for the property 'CompteIdcompte'
        }
        /// <summary>
        /// Test the property 'EvenementsIdevenements'
        /// </summary>
        [Test]
        public void EvenementsIdevenementsTest()
        {
            // TODO unit test for the property 'EvenementsIdevenements'
        }
        /// <summary>
        /// Test the property 'PhotoIdphoto'
        /// </summary>
        [Test]
        public void PhotoIdphotoTest()
        {
            // TODO unit test for the property 'PhotoIdphoto'
        }

    }

}
