/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Evenements
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EvenementsTests
    {
        // TODO uncomment below to declare an instance variable for Evenements
        //private Evenements instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Evenements
            //instance = new Evenements();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Evenements
        /// </summary>
        [Test]
        public void EvenementsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Evenements
            //Assert.IsInstanceOfType<Evenements> (instance, "variable 'instance' is a Evenements");
        }


        /// <summary>
        /// Test the property 'Idevenements'
        /// </summary>
        [Test]
        public void IdevenementsTest()
        {
            // TODO unit test for the property 'Idevenements'
        }
        /// <summary>
        /// Test the property 'Nom'
        /// </summary>
        [Test]
        public void NomTest()
        {
            // TODO unit test for the property 'Nom'
        }
        /// <summary>
        /// Test the property 'Datedebut'
        /// </summary>
        [Test]
        public void DatedebutTest()
        {
            // TODO unit test for the property 'Datedebut'
        }
        /// <summary>
        /// Test the property 'Datedefin'
        /// </summary>
        [Test]
        public void DatedefinTest()
        {
            // TODO unit test for the property 'Datedefin'
        }
        /// <summary>
        /// Test the property 'Motdepasseevent'
        /// </summary>
        [Test]
        public void MotdepasseeventTest()
        {
            // TODO unit test for the property 'Motdepasseevent'
        }

    }

}
