/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EvenementsAttentejsonld
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EvenementsAttentejsonldTests
    {
        // TODO uncomment below to declare an instance variable for EvenementsAttentejsonld
        //private EvenementsAttentejsonld instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EvenementsAttentejsonld
            //instance = new EvenementsAttentejsonld();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EvenementsAttentejsonld
        /// </summary>
        [Test]
        public void EvenementsAttentejsonldInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EvenementsAttentejsonld
            //Assert.IsInstanceOfType<EvenementsAttentejsonld> (instance, "variable 'instance' is a EvenementsAttentejsonld");
        }


        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Test]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'IdevenementsAttente'
        /// </summary>
        [Test]
        public void IdevenementsAttenteTest()
        {
            // TODO unit test for the property 'IdevenementsAttente'
        }
        /// <summary>
        /// Test the property 'Nom'
        /// </summary>
        [Test]
        public void NomTest()
        {
            // TODO unit test for the property 'Nom'
        }
        /// <summary>
        /// Test the property 'Datedebut'
        /// </summary>
        [Test]
        public void DatedebutTest()
        {
            // TODO unit test for the property 'Datedebut'
        }
        /// <summary>
        /// Test the property 'Datedefin'
        /// </summary>
        [Test]
        public void DatedefinTest()
        {
            // TODO unit test for the property 'Datedefin'
        }
        /// <summary>
        /// Test the property 'Motdepasseevent'
        /// </summary>
        [Test]
        public void MotdepasseeventTest()
        {
            // TODO unit test for the property 'Motdepasseevent'
        }
        /// <summary>
        /// Test the property 'Idcompte'
        /// </summary>
        [Test]
        public void IdcompteTest()
        {
            // TODO unit test for the property 'Idcompte'
        }

    }

}
