/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Photojsonld
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PhotojsonldTests
    {
        // TODO uncomment below to declare an instance variable for Photojsonld
        //private Photojsonld instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Photojsonld
            //instance = new Photojsonld();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Photojsonld
        /// </summary>
        [Test]
        public void PhotojsonldInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Photojsonld
            //Assert.IsInstanceOfType<Photojsonld> (instance, "variable 'instance' is a Photojsonld");
        }


        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Test]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Idphoto'
        /// </summary>
        [Test]
        public void IdphotoTest()
        {
            // TODO unit test for the property 'Idphoto'
        }
        /// <summary>
        /// Test the property 'Chemindacces'
        /// </summary>
        [Test]
        public void ChemindaccesTest()
        {
            // TODO unit test for the property 'Chemindacces'
        }
        /// <summary>
        /// Test the property 'Rawbytesqr'
        /// </summary>
        [Test]
        public void RawbytesqrTest()
        {
            // TODO unit test for the property 'Rawbytesqr'
        }

    }

}
