/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EvenementsAttenteApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EvenementsAttenteApiTests
    {
        private EvenementsAttenteApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EvenementsAttenteApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EvenementsAttenteApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EvenementsAttenteApi
            //Assert.IsInstanceOfType(typeof(EvenementsAttenteApi), instance, "instance is a EvenementsAttenteApi");
        }

        /// <summary>
        /// Test DeleteEvenementsAttenteItem
        /// </summary>
        [Test]
        public void DeleteEvenementsAttenteItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.DeleteEvenementsAttenteItem(id);
            
        }
        /// <summary>
        /// Test GetEvenementsAttenteCollection
        /// </summary>
        [Test]
        public void GetEvenementsAttenteCollectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //var response = instance.GetEvenementsAttenteCollection(page);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test GetEvenementsAttenteItem
        /// </summary>
        [Test]
        public void GetEvenementsAttenteItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetEvenementsAttenteItem(id);
            //Assert.IsInstanceOf<ComponentsschemasEvenementsAttentejsonld> (response, "response is ComponentsschemasEvenementsAttentejsonld");
        }
        /// <summary>
        /// Test PatchEvenementsAttenteItem
        /// </summary>
        [Test]
        public void PatchEvenementsAttenteItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //EvenementsAttente body = null;
            //var response = instance.PatchEvenementsAttenteItem(id, body);
            //Assert.IsInstanceOf<ComponentsschemasEvenementsAttentejsonld> (response, "response is ComponentsschemasEvenementsAttentejsonld");
        }
        /// <summary>
        /// Test PostEvenementsAttenteCollection
        /// </summary>
        [Test]
        public void PostEvenementsAttenteCollectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EvenementsAttente body = null;
            //var response = instance.PostEvenementsAttenteCollection(body);
            //Assert.IsInstanceOf<ComponentsschemasEvenementsAttentejsonld> (response, "response is ComponentsschemasEvenementsAttentejsonld");
        }
        /// <summary>
        /// Test PutEvenementsAttenteItem
        /// </summary>
        [Test]
        public void PutEvenementsAttenteItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //EvenementsAttente body = null;
            //var response = instance.PutEvenementsAttenteItem(id, body);
            //Assert.IsInstanceOf<ComponentsschemasEvenementsAttentejsonld> (response, "response is ComponentsschemasEvenementsAttentejsonld");
        }
    }

}
